# Site settings
title: Jason Kalwa
email: jason@jasonkalwa.com
description: > # Jason should probably write something here.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.jasonkalwa.com" # the base hostname & protocol for your site
twitter_username: jasonkalwa
github_username:  jasonkalwa
facebook_username: jasonkalwa

# Build settings
markdown: kramdown
